### PR TITLE
Add description for All Work Visible on One Board

### PR DESCRIPTION
**Pull request by mregazzi**
Now there is a description of All work visible on one board.

### CODE REVIEW

**Comment by JayBazuzi** [comment]
Cool of you to send this PR.

I think a key idea we should emphasize is the contrast with multiple boards, not just the visibility.

**Comment by mregazzi** [comment]
I do agree, for me it was a given: if there is some hidden work (not visible on the team board) then probably that work is tracked on another tool, file, board, sheet whatever. We should integrate, is it fine for you  @JayBazuzi ? (so, adding without changing)

**Comment by mregazzi** [comment]
I would change that sentence in "If it is not on the one true board, it doesn't exist." - I think we should ask Arlo to have those permission, otherwise it is almost a waste of time (I created a branch and a parallel page, but I prefer to support this rather than have a new one)

**Comment by arlobelshee** [comment]
I owe you a more thought out response than I can give tonight. So for now I
just want to say thank you!

I'll take some time to read this pr tomorrow and help you get it merged -
in one form or another. Thank you very much for filling in one of my many
missing descriptions!

Arlo Belshee
Distinguished Engineer
***@***.***
http://digdeeproots.com/
@arlobelshee   in:arlobelshee

**Comment by arlobelshee** [comment]
I have some updates I want to make. It looks easiest to accept this PR and then add subsequent commits. Doing so now.

**Pull request merged**
