### PR TITLE
F!! Add "Intentional Technical Debt"

### PR DESCRIPTION
**Pull request by JayBazuzi**

### CODE REVIEW

**Comment by JayBazuzi** [comment]
@arlobelshee would you consider this as an MVP?

**Comment by nitsanavni** [comment]
@JayBazuzi _when_ is it appropriate to intentionally take on tech debt? And _why_ do it?

**Comment by JayBazuzi** [comment]
First, about the prerequisite `Pay down technical debt`:

Most organizations create technical debt continuously, and rarely pay it down.

They may intend to do so eventually ("we'll clean this up after the current pressing work is done") but then it doesn't happen. There's always more pressing work to do. Kinda like a kid who says they'll clean their room tomorrow - always tomorrow. It's a lie we tell ourselves. 

In these organizations, we should never agree to defer refactoring, cleaning, adding tests, and so on.


Only organizations with a demonstrated track record of prioritizing cleanup over features and bug fixes are able to _temporarily_ swap that prioritization, defer some cleanup work and _actually_ come back to it soon.

**Comment by JayBazuzi** [comment]
Second, about why this helps with `Hypothesis stories`:

Suppose we have a feature idea that we want to test. Most ideas are wrong; most experiments "fail"*. The faster we find that out, the more experiments we can run before the seed capital runs out. This is great! Let's not bother with a bunch of architectural refactoring when we're probably gonna throw it all out anyway.

When we're in an "Explore" phase we prioritize number of experiments run over clean code in the short term, knowing this will create an exorbitant ongoing cost in the medium term, and that is the right trade-off.

\* actually the experiment is *successful* if it answers the question of whether the idea is viable.

**Pull request merged**
